### ISSUE TITLE
connecting with forRootAsync doesn't work

### ISSUE THREAD

**Issue by smileeunsong** [kkoomen/nestjs-throttler-storage-redis#1480]
Hello,
I have been trying to connect redis storage to nest throttler. But connection with forRootAsync keeps failing.

<br>

It works in case of forRoot.
```JavaScript
ThrottlerModule.forRoot({
  throttlers: [
    {
      ttl: 60,
      limit: 10,
    },
  ],
  storage: new ThrottlerStorageRedisService(new Redis()),
})
```
<br>

But it is not in forRootAsync using `useFactory`.
```JavaScript
ThrottlerModule.forRootAsync({
  inject: [ConfigService],
  useFactory: async (config: ConfigService) => [
    {
      ttl: config.get<ThrottleConfig>('throttle').ttl,
      limit: config.get<ThrottleConfig>('throttle').limit,
      storage: new ThrottlerStorageRedisService(new Redis()),
    },
  ],
})
```

<br>

I've checked on `redis-cli monitor`, and even tried this but failed again.
```JavaScript
ThrottlerModule.forRootAsync({
  inject: [ConfigService],
  useFactory: async (config: ConfigService) => {
    const redisClient = new Redis();

    const test = () => {
      return new Promise((resolve, reject) => {
        redisClient.on('connect', () => {
          resolve(true);
        });
        redisClient.on('error', () => {
          reject(false);
        });
      });
    };

    await test();

    return [
      {
        ttl: config.get<ThrottleConfig>('throttle').ttl,
        limit: config.get<ThrottleConfig>('throttle').limit,
        storage: new ThrottlerStorageRedisService(
          redisClient,
        ),
      },
    ];
```

packages:
```JavaScript
"ioredis": "^5.3.2",
"nestjs-throttler-storage-redis": "^0.4.1",
"@nestjs/throttler": "^5.0.1"
```

Has anyone got this problem?

**Comment by jmcdo29** [comment]
Can you show specifically how it's failing? Maybe provide a reproduction with docker-compose to run redis?

**Comment by smileeunsong** [comment]
@jmcdo29 I didn't set docker to run redis. It is on aws elasticache for production level, and before to connect that, I have been trying to do a test with my local redis. It's weird that forRoot connection works, but forRootAsync connection doesn't. Please let me know if I misunderstood what you are meaning.

**Comment by jmcdo29** [comment]
> how can I show you it's falling

Providing the error is a good way to do that

> I didn't set docker to run redis

But can you for a minimum reproduction? A way for us to run things locally and see the same failure

**Comment by smileeunsong** [comment]
config :
```yml
throttle:
  ttl: 1000
  limit: 1
```

forRootAsync :
```Javascript
ThrottlerModule.forRootAsync({
  inject: [ConfigService],
  useFactory: async (config: ConfigService) => [
    {
      ttl: config.get<ThrottleConfig>('throttle').ttl,
      limit: config.get<ThrottleConfig>('throttle').limit,
      storage: new ThrottlerStorageRedisService(new Redis()),
    },
  ],
})
```

https://github.com/kkoomen/nestjs-throttler-storage-redis/assets/111448985/25458ce5-9eaf-42dc-b825-b020378699fe

forRoot :
```Javascript
ThrottlerModule.forRoot({
  throttlers: [
    {
      ttl: 1000,
      limit: 1,
    },
  ],
  storage: new ThrottlerStorageRedisService(new Redis()),
})
```

https://github.com/kkoomen/nestjs-throttler-storage-redis/assets/111448985/508d8055-da90-4f0f-9480-c94cefcb7338

Error Message :
```
[11:40:48.911] ERROR (53006):
    instanceId: "Adamui-MacBookPro.local"
    stack: "ThrottlerException: ThrottlerException: Too Many Requests\n    at ThrottlerBehindProxyGuard.throwThrottlingException (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/throttler/src/throttler.guard.ts:185:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ThrottlerBehindProxyGuard.handleRequest (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/throttler/src/throttler.guard.ts:131:7)\n    at ThrottlerBehindProxyGuard.canActivate (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/throttler/src/throttler.guard.ts:90:22)\n    at GuardsConsumer.tryActivate (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/core/guards/guards-consumer.js:16:17)\n    at canActivateFn (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/core/router/router-execution-context.js:134:33)\n    at /Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/core/router/router-execution-context.js:42:31\n    at Object.<anonymous> (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/core/router/router-proxy.js:9:17)"
ThrottlerException: ThrottlerException: Too Many Requests
    at ThrottlerBehindProxyGuard.throwThrottlingException (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/throttler/src/throttler.guard.ts:185:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ThrottlerBehindProxyGuard.handleRequest (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/throttler/src/throttler.guard.ts:131:7)
    at ThrottlerBehindProxyGuard.canActivate (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/throttler/src/throttler.guard.ts:90:22)
    at GuardsConsumer.tryActivate (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/core/guards/guards-consumer.js:16:17)
    at canActivateFn (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/core/router/router-execution-context.js:134:33)
    at /Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/core/router/router-execution-context.js:42:31
    at Object.<anonymous> (/Users/adampark/Documents/server-youngface-nest/node_modules/@nestjs/core/router/router-proxy.js:9:17) {
  response: 'ThrottlerException: Too Many Requests',
  status: 429,
  options: undefined
}
```

I am not sure this is a good way to show reproduction, but hope it helps.

**Comment by jmcdo29** [comment]
Are you not expecting a 429?

**Comment by smileeunsong** [comment]
Because the throttler is set (ttl: 1000, limit:1), I am expecting 429 when a request goes twice in 1 sec.
But the problem is that nestjs throttler is not using redis with forRootAsync connection. I guess in-memory cache is used for that.

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by smileeunsong** [comment]
@jmcdo29 
https://github.com/smileeunsong/minimum-reproduction-nestjs-throttler-storage-redis

Thank you for your patience. This is the first time I learned about minimum reproduction.
ThrottlerModule.forRootAsync part is commented out. I tested it with curl http://localhost:3000 & redis-cli monitor.

**Comment by jmcdo29** [comment]
Ah, I see, you have an incorrect configuration for the `ThrottlerModule` in the `forRootAsync` setup. It should be 

```ts
ThrottlerModule.forRootAsync({
  useFactory: async () => ({
    throttlers: [
      {
        ttl: 1000,
        limit: 1,
      },
    ],
    storage: new ThrottlerStorageRedisService(new Redis({)),
  }),
}),
```

Notice that the factory returns an object, not just an array, and that `storage` lives _outside_ the `throttlers` array.

**Comment by smileeunsong** [comment]
It works! Thank you for your help :)
Maybe we can update [Usage part](https://github.com/kkoomen/nestjs-throttler-storage-redis#usage) in README.md for the others.

```javascript
ThrottlerModule.forRootAsync({
  imports: [ConfigModule],
  inject: [ConfigService],
  useFactory: (config: ConfigService) => ({
    throttlers: [
      {
        ttl: config.get('THROTTLE_TTL'),
        limit: config.get('THROTTLE_LIMIT'),
      },
    ],
    storage: new ThrottlerStorageRedisService(new Redis()),
  }),
})
```

**Comment by kkoomen** [comment]
Thanks all for figuring this out, and thanks to @smileeunsong for the suggestion. I didn't adjust _all_ examples unfortunately. I just updated the README with your suggestion :)
