### ISSUE TITLE
version issue 

### ISSUE THREAD

**Issue by alabbas-ali** [kkoomen/nestjs-throttler-storage-redis#1670]
"reflect-metadata": "^0.2.2",
"cache-manager": "^5.5.1",
"cache-manager-ioredis-yet": "^2.0.3",
"nestjs-throttler-storage-redis": "^0.4.4",
"@nestjs/cache-manager": "^2.2.2",

"ioredis": "^5.4.0" or "^5.3.2"

code 

```
import { Injectable, Logger, LoggerService } from '@nestjs/common'
import { ConfigService } from '@nestjs/config'
import {
    ThrottlerModuleOptions,
    ThrottlerOptions,
    ThrottlerOptionsFactory
} from '@nestjs/throttler'

import { ThrottlerStorageRedisService } from 'nestjs-throttler-storage-redis'
import { RedisOptions } from 'ioredis'

import { ConfigEnum } from './config'

@Injectable()
export class ThrottlerConfig implements ThrottlerOptionsFactory {
    private readonly logger: LoggerService = new Logger(ThrottlerConfig.name)

    constructor(private readonly configService: ConfigService) {}

    createThrottlerOptions(): ThrottlerModuleOptions {
        const throttlers = this.configService.get<ThrottlerOptions>(
            ConfigEnum.THROTTLER
        ) ?? {
            ttl:
                this.configService.get<number>(ConfigEnum.THROTTLE_TTL) ??
                600000,
            limit:
                this.configService.get<number>(ConfigEnum.THROTTLE_LIMIT) ?? 20
        }

        const redisOptions = this.configService.get<RedisOptions>(
            ConfigEnum.REDIS_URL
        )

        this.logger.log('ThrottlerConfig.createThrottlerOptions', redisOptions)

        return {
            throttlers: [throttlers],
       -> -> ->    storage: new ThrottlerStorageRedisService(redisOptions)
        }
    }
}

```

model:

```
ThrottlerModule.forRootAsync({
            imports: [ConfigModule],
            useClass: ThrottlerConfig
        }),
 ```
 
 errror:
 
 ```
 [Nest] 16928  - 04/17/2024, 2:18:26 PM   ERROR [ExceptionsHandler] ERR Error running script (call to f_f7788d43191d9ad66c866e8c63f3c3e361391849): @user_script:5: @user_script: 5: Lua redis() command arguments must be strings or integers
ReplyError: ERR Error running script (call to f_f7788d43191d9ad66c866e8c63f3c3e361391849): @user_script:5: @user_script: 5: Lua redis() command arguments must be strings or integers
    at parseError (C:\Users\weeam\one-cp\one-cp-proxy\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\Users\weeam\one-cp\one-cp-proxy\node_modules\redis-parser\lib\parser.js:302:14)
 ```
 
 disable the line `storage: new ThrottlerStorageRedisService(redisOptions)` code work fine

**Comment by kkoomen** [comment]
Hi,

I have zero clue about what could cause this for now. The tests on my side are all passing and in the end, my plugin is just a NestJS wrapper package for Redis with support for single or cluster instances.

Try to make a minimal demo with e.g. just NestJS and this plugin and TS that makes a connection in the preferred project structure you'd like and see if you can make it work with this minimal setup. Try to debug versions. You know my tests are passing so perhaps you use different Redis versions or use other plugins that can clash with redis that make it look like it's coming from my package, but it's not. I also have had it before where it seems like it's my package, but it wasn't.
